### ISSUE TITLE
You didn't upload on github pages

### ISSUE THREAD

**Issue by TheKingLol** [Zyst3rx/Gaming.github.io#1]
This website looks cool but it is not deployed yet.
Here 
https://docs.github.com/en/pages/quickstart

**Comment by TheKingLol** [comment]
https://github.com/Zyst3rx/Gaming.github.io/settings/pages
I think you should go here instead

**Comment by Zyst3rx** [comment]
https://zyst3rx.github.io/Gaming.github.io

**Comment by TheKingLol** [comment]
Thanks, this looks cool, going to close the issue now
